# .travis.yml 文件

# 声明构建语言环境
language: android
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-29.0.3
    - android-26
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
before_script:
    - chmod +x gradlew
    - chmod +x .travis/*
    
before_install:
- yes | sdkmanager "platforms;android-29" # workaround for accepting the license
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_5ba4ee4c096f_key -iv $encrypted_5ba4ee4c096f_iv -in "$PWD/.travis/secrets.tar.enc" -out secrets.tar -d;
    tar xf secrets.tar;
  fi
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
  # 生成 APK
  - ./gradlew assembleRelease
  - .travis/build.sh && .travis/create-repo.sh
# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: $GIT_TOKEN
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/release/PlayVideo*.apk
  file_glob: true
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    repo: Haleydu/playVideo
    all_branches: true
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: 'true'
