# .travis.yml 文件

# 声明构建语言环境
language: android
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-29.0.3
    - android-26
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
before_script:
    - chmod +x gradlew
script:
  # 生成 APK
  - ./gradlew assembleRelease

# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key:
    secure: fQsq+ckCIddediuo0kpA9HEPXmuHIL+qstaIVpkSBSLerHt0v3ppla8RURgQod3Esd6gd1p/zBeae5ipGlwTe1IHmr77NTSGHRFBdvAktXEeXjFfGDFNAX3eK8uaPznhcwIyf+KR0qcBJGKADECrl+bO/TqA0oNS1z8xJJxmhljQp2zmWLM8kHNtv8L8Xi+Ss3KpRTapJOkqNZOGP6LChs53vLp3fF53n2Iutze9JNfn5c0NxBb1kOUAS4ghD17IlKkwdKwxp/Hka7cHb72yR2bPP7NiELcWtY2HhZunqen2n5ge8jvWf9MP/IODH7rvM5IHP1uslAgyvCdQa+u7YmhB3i4PhEkjyZhKi7oMa8RIBJmddFjZrpqxZJfMKGu5/DnZrSD+2gGIFzKlZKfuYqM8PG1TYNz7hea/BdiSreI7nOV5Nye44pMFkKi3mSc/9ViPjPCQbBpDzHGRce1K5x+LXw4kGP9OG4MURsMNZKKSNdEuOS6xTLlsEAGI97pl/KksJmi9xGouGRm9QVuSRCUzTtI4CEBKjCThBs5c0otJnxNqN0hdvOPCuniHwiaukNFOxF3SGR9izR4agcBCO7dOry1YsgUX6kLTSCSlhlGJkyJIZ291dgTCC9o4tOfpMyKKoG8iIA5gBupDLu/rrMcYYODIxI/IwuZGwRu/6w8=
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/release/PlayVideo.apk
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    repo: Haleydu/playVideo
    all_branches: true
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: 'true'
